# Generated by Django 5.0.4 on 2024-04-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
    ]
